export { default as Header } from './Header'
export { default as MovieListView } from './MovieListView'
export { default as Footer } from './Footer'
export { default as MovieCard } from './MovieCard'
export { default as TrailerModal } from './TrailerModal'
export { default as Pagination } from './Pagination'
export { default as SplashScreen } from './SplashScreen'